prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "time",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "battery",
    "memory_usage",
    "line_break",
    "jobs",
    "character",
]


[character]      
symbol = "λ"     # The "symbol" segment is being set to "λ"

[time]
disabled = false
format = "%R"
